import { Token } from "./token.d.js";

let tokens: Token[] = [
  {
    name: "HANA",
    address: "0xb3912b20b3abc78c15e85e13ec0bf334fbb924f7",
    buyTimestamp: NaN,
    historyPrice: [],
    buyPrice: NaN,
    highPrice: NaN,
    buyAmount: 0,
    buyEthCost: NaN,
    buyGasUsed: 0,
    sellGasUsed: 0,
    profit: 0,
    tradeWin: 21,
    tradeCount: 26,
  },
  {
    name: "MOODENG",
    address: "0x28561b8a2360f463011c16b6cc0b0cbef8dbbcad",
    buyTimestamp: NaN,
    historyPrice: [],
    buyPrice: NaN,
    highPrice: NaN,
    buyAmount: 0,
    buyEthCost: NaN,
    buyGasUsed: 0,
    sellGasUsed: 0,
    profit: 0,
    tradeWin: 10,
    tradeCount: 10,
  },
  {
    name: "ESTEE",
    address: "0x4298e4ad48be89bf63a6fdc470a4b4fe9ce633b1",
    buyTimestamp: NaN,
    historyPrice: [],
    buyPrice: NaN,
    highPrice: NaN,
    buyAmount: 0,
    buyEthCost: NaN,
    buyGasUsed: 0,
    sellGasUsed: 0,
    profit: 0,
    tradeWin: 6,
    tradeCount: 11,
  },
];

export default { tokens };
